// <auto-generated />
using System;
using CMPT395Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMPT395Project.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20181031050114_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CMPT395Project.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("AdminId");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("CMPT395Project.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName");

                    b.HasKey("CompanyId");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("CMPT395Project.Models.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActiveContract")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.Property<int>("CompanyId");

                    b.Property<int>("ContractorId");

                    b.Property<int>("P1CharRate");

                    b.Property<DateTime>("P1EndtDate");

                    b.Property<int>("P1PayRate");

                    b.Property<DateTime>("P1StartDate");

                    b.Property<int>("P2CharRate");

                    b.Property<DateTime>("P2EndtDate");

                    b.Property<int>("P2PayRate");

                    b.Property<DateTime>("P2StartDate");

                    b.Property<int>("P3CharRate");

                    b.Property<DateTime>("P3EndtDate");

                    b.Property<int>("P3PayRate");

                    b.Property<DateTime>("P3StartDate");

                    b.Property<int>("P4CharRate");

                    b.Property<DateTime>("P4EndtDate");

                    b.Property<int>("P4PayRate");

                    b.Property<DateTime>("P4StartDate");

                    b.Property<string>("Renewal");

                    b.HasKey("ContractId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContractorId");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("CMPT395Project.Models.Contractor", b =>
                {
                    b.Property<int>("ContractorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId");

                    b.Property<int?>("ContracsContractId");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.HasKey("ContractorId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ContracsContractId");

                    b.ToTable("Contractor");
                });

            modelBuilder.Entity("CMPT395Project.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("CMPT395Project.Models.EmployeeHour", b =>
                {
                    b.Property<int>("TimeSheetId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContractId");

                    b.Property<int>("CurrentMonth");

                    b.Property<int>("Month");

                    b.Property<int>("PreviousMonth");

                    b.Property<int>("Year");

                    b.HasKey("TimeSheetId");

                    b.HasIndex("ContractId");

                    b.ToTable("EmployeeHour");
                });

            modelBuilder.Entity("CMPT395Project.Models.Contract", b =>
                {
                    b.HasOne("CMPT395Project.Models.Company", "Company")
                        .WithMany("Contracts")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("ForeignKey_Contract_Company")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CMPT395Project.Models.Contractor", "Contractor")
                        .WithMany("Contracts")
                        .HasForeignKey("ContractorId")
                        .HasConstraintName("ForeignKey_Contract_Contractor")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CMPT395Project.Models.Contractor", b =>
                {
                    b.HasOne("CMPT395Project.Models.Company", "Company")
                        .WithMany("Contractors")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("ForeignKey_Contractor_Company")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CMPT395Project.Models.Contract", "Contracs")
                        .WithMany()
                        .HasForeignKey("ContracsContractId");
                });

            modelBuilder.Entity("CMPT395Project.Models.EmployeeHour", b =>
                {
                    b.HasOne("CMPT395Project.Models.Contract", "Contract")
                        .WithMany("EmployeeHours")
                        .HasForeignKey("ContractId")
                        .HasConstraintName("ForeignKey_EmployeeHours_Contractor")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
